const fs=require('fs'),vm=require('vm'),crypto=require('crypto');
const html=fs.readFileSync('outputs/index.html','utf8');const scripts=[...html.matchAll(/<script[^>]*>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
function context(){const storage=new Map(),nodes=new Map();function node(){return {style:{},classList:{add(){},remove(){}},addEventListener(){},removeEventListener(){},click(){}}};const c=vm.createContext({console,URLSearchParams,Date,setTimeout,clearTimeout,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},window:{addEventListener(){},location:{hash:'',pathname:'/',search:''}},document:{documentElement:{setAttribute(){}},getElementById:id=>{if(!nodes.has(id))nodes.set(id,node());return nodes.get(id)},querySelector:()=>node()},fetch:()=>{throw Error('NETWORK FORBIDDEN')}});scripts.forEach(s=>vm.runInContext(s,c));return c}

const c=context(),run=code=>vm.runInContext(code,c,{timeout:5000}),out={};
out.phases=run("generateAdaptivePlan({profile:defaultProfile(),goal:defaultGoal(),availability:defaultAvailability(),limitations:[]}).weeks.map(w=>w.phase)");
out.weeklyMissingRpe=run("weeklyReview([{id:'a',category:'running',planned:{rpe:'3-4'}},{id:'b',category:'running',planned:{rpe:'3-4'}}],{a:{status:'completed'},b:{status:'completed'}},{priorWeeks:[{sessionsCount:3}]}).decision");
out.matrix=run(`(()=>{let n=0,problems=[];for(const days of [0,1,6,7,13,14,21,28,35,59,63,120])for(const level of ['principiante','intermedio','avanzado'])for(const daysAvailable of [[],[1],[1,2,3],[1,3,6],[0,1,2,3,4,5,6]]){const goal={...defaultGoal(),startDate:'2026-09-16',date:addDays('2026-09-16',days)};const ctx={profile:{...defaultProfile(),level},goal,availability:{...defaultAvailability(),days:daysAvailable},limitations:[]};const p=generateAdaptivePlan(ctx);enrichPlan(p,ctx);const d=p.weeks.flatMap(w=>w.days);n++;if(d.length!==days+1||d.filter(x=>x.type==='RACE').length!==1||new Set(d.map(x=>x.date)).size!==d.length)problems.push({days,level,daysAvailable});}return {cases:n,calendarInvariantFailures:problems}})()`);
out.schema0=run("(()=>{state=f13_2_blankAthleteState();state.races=[];state.planCurrent={weeks:[{n:1,days:[]}]};f12EnsureState();return {active:state.activeRaceId,planRemains:!!state.planCurrent}})()");
out.multiRaceDirty=run("(()=>{state=f13_2_blankAthleteState();const a=f12CreateRace({date:'2026-11-20'});f12SetActiveRace(a.id);ensurePlan();const b=f12CreateRace({date:'2026-12-20'});f12SetActiveRace(b.id);ensurePlan();state.availability.days=[];markConfigDirty();f12SetActiveRace(a.id);return {dirty:state.configDirty,stillRunning:allSessions().some(s=>s.category==='running'),availability:state.availability.days}})()");
out.generationCounters=run("(()=>{state=f13_2_blankAthleteState();state.races=[{id:'a',distanceKm:5,date:'2026-10-01'},{id:'a',distanceKm:10,date:'2026-11-01'}];f12EnsureState();return {races:state.races.length,cycles:Object.keys(state.raceCycles).length}})()");
fs.writeFileSync('work/audit/supplement.json',JSON.stringify(out,null,2));console.log(JSON.stringify(out,null,2));
